In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
A=np.arange(21)

In [7]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
B=A[A%2==0]

In [9]:
B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
C=A[A%3==0]

In [11]:
C

array([ 0,  3,  6,  9, 12, 15, 18])